/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check


/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  lmosSidebar: [
    "introduction",
    "who_is_it_for",
    "agent",
    "tool",
    "getting_started",
    {
      type: 'category',
      label: 'Multi-Agent System',
      collapsible: true,
      collapsed: false,
      items: [
        'multi_agent_system/overview',
        'multi_agent_system/agent_description',
        'multi_agent_system/agent_discovery',
        'multi_agent_system/agent_registry',
        'multi_agent_system/agent_communication',
        'multi_agent_system/group_management',
        'multi_agent_system/agent_lifecycle'
      ],
    },
    {
      type: 'category',
      label: 'LMOS Protocol',
      collapsible: true,
      collapsed: false,
      items: [
        'lmos_protocol/introduction',
        'lmos_protocol/requirements',
        'lmos_protocol/agent_description',
        'lmos_protocol/tool_description',
        'lmos_protocol/communication_protocol',
        'lmos_protocol/observability',
        'lmos_protocol/security',
        'lmos_protocol/websocket_binding'
      ],
    },
    {
      type: 'category',
      label: 'LMOS Platform',
      collapsible: true,
      collapsed: false,
      items: [
        'lmos_platform/overview',
        'lmos_platform/lmos_control_plane',
        'lmos_platform/lmos_router',
        'lmos_platform/lmos_runtime',
      ],
    },
  ],
  arcSidebar: [
    {
      type: 'autogenerated', 
      dirName: 'arc'
    }
  ],
};

export default sidebars;
